package example;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ExampleTest {

    @Test
    public void profileEnumTest() {

        long start = System.currentTimeMillis();

        while (true) {

            ExampleEnum[] vals = ExampleEnum.values();

            long now = System.currentTimeMillis();
            if (now - start > 2000) {
                break;
            }

        }

        assertTrue(true);

    }

}
